site_name: 5-sterren model voor transparante algoritmes
theme:
  name: material
  font: 
    text: Karla
  palette: 
    primary: teal
  features: 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  nav:
    - Home: index.md
    - Toolkit: 
      - Whitepaper / visiedocument: whitepaper.md
      - Model / keuzehulp: model.md
  
